package edu.ubb.cwmdEjb.model;

public enum LogActionType {
	DOCUMENT_MODIFICATION,
	DOCUMENT_CREATION,
	DOCUMENT_DELETION,
	PASSWORD_RESET,
	USER_DATA_MODIFICATION,
	USER_CREATION,
	FLOW_STARTED,

}
